### ISSUE TITLE
Command functionality

### ISSUE THREAD

**Issue by KarachentsevDanil** [hlaueriksson/CommandQuery#1]
Hi, I have got acquainted with your source code and it is excellent and easy to use library. But for now, there is no opportunity to return result from command. Is it in plat to implement this functionality or no?

**Comment by hlaueriksson** [comment]
I followed the dogmatic approach to commands described by [Martin Fowler](https://martinfowler.com/bliki/CommandQuerySeparation.html):

> Commands: Change the state of a system but do not return a value.

In theory this sounds good, but in practice it can be inconvenient.

I will consider this for the next release:

`public interface ICommand<TResult> { }`

**Comment by KarachentsevDanil** [comment]
@hlaueriksson Cool, thank you very match.

**Comment by hlaueriksson** [comment]
Version `0.9.0` of `CommandQuery` now supports commands with result.

Documentation:
https://github.com/hlaueriksson/CommandQuery/blob/master/CommandQuery.md

The sample code is updated:
https://github.com/hlaueriksson/CommandQuery/tree/master/samples
